server:
  port: 8082
spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL
